### ISSUE TITLE
Implement test phases

### ISSUE THREAD

**Issue by alco** [alco/benchfella#11]
It should be possible to have a setup phase, running phase, and teardown phase, all measured separately.

This will allow comparing sequential algorithms to parallel ones without adding the overhead of spawning processes into every iteration.

**Comment by mroth** [comment]
Just chiming in to say a per file/module setup and teardown callback would be _extremely_ useful.

Currently if you have something loaded for an individual test, there is no way to unload it after the completion of that test, and if you are running multiple benchmark scripts via `mix bench`, it affects all of them. (I ran into this while using Meck to stub out an expensive function to isolate a benchmark).

**Comment by alco** [comment]
Thanks for the feedback, @mroth. I'm going to take a closer look at this in the coming days and see what I can come up with.

A quick question: will having a pair of setup and teardown callbacks that run before and after each test case be sufficient for your extwitter PR? Because I got the impression that you want benchfella to reset the VM state between running individual benchmarks (which code is loaded is part of the VM state) and that's something not even ExUnit does.

**Comment by mroth** [comment]
@alco yes, setup and teardown callbacks would be sufficient, either defined globally for a script file / module or per test would work!  thank you for looking into it.

**Comment by alco** [comment]
Implemented in https://github.com/alco/benchfella/commit/80b83538f6233da3a428d53e5047311cb2b6fbec.
