### ISSUE TITLE
--mem-stats breaks

### ISSUE THREAD

**Issue by alexrp** [alco/benchfella#18]
I don't know if memory stats are actually fully implemented yet, but:

    $ mix bench --mem-stats
    ** (exit) bad cast: {:remote_dispatch, Binary}
    $ mix bench --sys-mem-stats
    ** (exit) bad cast: {:remote_dispatch, Binary}

**Comment by PragTob** [comment]
Seems mem_stats has been removed, so I guess this can be closed? :)

**Comment by alco** [comment]
@PragTob indeed.
