### ISSUE TITLE
Automatically compile/compile.protocols before runnings benchmarks

### ISSUE THREAD

**Issue by devinus** [alco/benchfella#21]
If run from within a project.

**Comment by alco** [comment]
On the [latest master](https://github.com/alco/benchfella/commit/51cabb22c4fef1cd2dc1777e38c7d83d404c13f1) Benchfella invokes `app.start --no-start` for the host project. If that project has `consolidate_protocols: true` or `build_embedded: true` in its configuration, benchmarks will run with consolidated protocols.
