### ISSUE TITLE
Experiment with a markdown formatter

### ISSUE THREAD

**Issue by alco** [alco/benchfella#28]
Prompted by this [gist](https://gist.github.com/lexmag/32977ce8fd7cb44ddefa) by @lexmag. Could be a useful addition.

**Comment by lexmag** [comment]
Hey @alco, what are your thoughts about adding new CLI option for that purpose, e.g `--format=plain|raw|markdown`. Probably it'll be a replacement for a `--no-pretty` one?

**Comment by alco** [comment]
Sounds good, only it conflicts with the existing `--format` option on `bench.cmp`.

Both `mix bench` and `mix bench.cmp` (when it is passed a single path) call `Snapshot.pretty_print` to format the results. The ability to pretty-print stored snapshots in any supported format is essential, but it's current implementation as part of `mix bench.cmp` might not be ideal.

In any case, `bench.cmp` should also support markdown output or at least be able to format a table using ASCII characters. That leaves us with the task of renaming its current `--format` option. I'm thinking `--diff-format` or `--units`, or `--algorithm`.

Which one do you prefer, @lexmag?

**Comment by lexmag** [comment]
Aa for me just `--diff` feels pretty fine (e.g. `mix bench.cmp --diff percent`). I think `--units` or `--algorithm` aren't good match. We could also check what [thesaurus.com](http://www.thesaurus.com/browse/difference?s=ts) has for naming. :bowtie:
