### ISSUE TITLE
Error when writing snapshot on Windows.

### ISSUE THREAD

**Issue by rossjones** [alco/benchfella#38]
When using ```{:benchfella, "~> 0.2.0"}``` I get an error when running a benchmark on Windows when trying to write the snapshot

The error message is:

```
Finished in 4.81 seconds
** (File.Error) could not write to file bench/snapshots/2015-07-30T10:40:52.snapshot: I/O error
    (elixir) lib/file.ex:635: File.write!/3
    lib/benchfella.ex:184: Benchfella.print_formatted_data/3
    (elixir) lib/kernel/cli.ex:70: anonymous fn/3 in Kernel.CLI.exec_fun/2
```

**Comment by rossjones** [comment]
This appears to be related to the format of the filename.  Exploratory poking leads to:

```
iex(5)> File.write("2015-07-30T10_41_23.snapshot", "somedata")
:ok
iex(6)> File.write("2015-07-30T10:41_23.snapshot", "somedata")
:ok
iex(7)> File.write("2015-07-30T10:41:23.snapshot", "somedata")
{:error, :eio}
```

So it appears to be the presence of two ```:``` although it works fine with one.  Will investigate whether this is Windows specific, or an elixir/erlang bug.

**Comment by rossjones** [comment]
: is a reserved character on windows and can't be used in filenames (although erlang seems to let one through).  Would you be open to a PR that replaces : with - in the filename?

**Comment by alco** [comment]
Thanks for investigating this. I would go with this format: `2015-07-30_10-41-23.snapshot`. A PR will be appreciated.

**Comment by alco** [comment]
Fixed in https://github.com/rossjones/benchfella/commit/18d3326dad02db36d3b7110c9d0439982a0e8940
