### ISSUE TITLE
mix bench throw error

### ISSUE THREAD

**Issue by killme2008** [alco/benchfella#41]
I tried to run the example as described in README,but got error:

```
== Compilation error on file lib/benchmark.ex ==
** (RuntimeError) Benchfella is not started
    lib/benchfella.ex:359: Benchfella.add_bench/2
    lib/benchmark.ex:7: (module)
    (stdlib) erl_eval.erl:669: :erl_eval.do_apply/6
```

**Comment by killme2008** [comment]
My issue, forget it,sorry.

**Comment by bitmage** [comment]
@killme2008 it would be helpful if you mentioned your fix.  :-)

I am apparently making the same mistake.

**Comment by bitmage** [comment]
Adding `Benchfella.start` to the example resolved the issue.

```exs
defmodule BM do
  use Benchfella
  Benchfella.start

  @list []
  bench "hello list" do
    @list.push 0.2 + 0.1
  end
end
```

Should this be necessary?  Shouldn't I be able to start benchfella by adding it to the applications in mix.exs?  Documentation around expected procedure would help.

Thanks!

**Comment by alco** [comment]
@bitmage 
You don't need to start it nor put it in the list of applications. If you put your `_bench.exs` files into the `bench/` directory and then run `mix bench`, it'll work as described in Readme.

**Comment by bitmage** [comment]
I see.  Thank you!
