### ISSUE TITLE
Please what am i doing wrong here?

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [alco/benchfella#42]
Location: c:/Users/Charl/.mix/archives/benchfella-0.2.1.ez/benchfella-0.2.1/ebin

D:\Elixir>mix bench "d:\elixir\bench\basic_bench.exs"
** (Mix) Could not find a Mix.Project, please ensure a mix.exs file is available

D:\Elixir>

**Comment by alco** [comment]
@CharlesOkwuagwu Have you figured it out? Benchfella should be run inside a Mix project, so normally you'd create one, put your benchmark definition in a file under `bench/` and then execute `mix bench`.

**Comment by CharlesOkwuagwu** [comment]
Thanks, Yeah I got that eventually. It's not so clear in your install option-1. I think you shold explicitly state that in you instructions. :)

Also I had to download and compile master to fix the file-name bug on windows.

**Comment by alco** [comment]
@CharlesOkwuagwu Yeah, sorry about that. I have just pushed a new release with the bug fixes and also updated the Readme. I'm no longer supporting the archive since Benchfella needs to be run a Mix project anyway.
