### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by hunterboerner** [alco/benchfella#49]
Erlang 19. Elixir 1.3.2

```
** (CompileError) lib/benchfella/snapshot.ex:46: Benchfella.Snapshot.__struct__/1 is undefined, cannot expand struct Benchfella.Snapshot
```

**Comment by alco** [comment]
It works here. Which version of Benchfella? Did you try cleaning the project and recompiling from scratch?

**Comment by hunterboerner** [comment]
6a6abf836d4afbd2ab3b9a44fbc41afbba6a43e2 (master) and whatever the latest hex version is.

**Comment by ismaelga** [comment]
I had this same problem.

Removing the old benchafella archive solved it.
`mix archive.uninstall benchfella-0.?.?.ez`
