### ISSUE TITLE
Is there a way to distinguish normal run and bench?

### ISSUE THREAD

**Issue by Hinidu** [alco/benchfella#62]
Hello and thank you for your work!
It's very useful to me that I can distinguish test runs and normal runs using `Mix.env`. Is it possible to run benchmarks in a different environment? Or distinguish benchmark runs another way?

**Comment by alco** [comment]
@Hinidu I don't think Benchfella cares about the current environment. You should be able to set `MIX_ENV` to any value before running benchmarks.

**Comment by Hinidu** [comment]
@alco Thank you! I think it's the simplest way to do what I want.
